name: Content Review - Tone of Voice Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.mdx'
      - '!snippets/**'
      - '!**/installation.mdx'
      - '!**/implementation.mdx'
      - '!**/triggermodal.mdx'
      - '!**/about/**'

jobs:
  content-review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed MDX files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.mdx
          files_ignore: |
            snippets/**
            **/installation.mdx
            **/implementation.mdx
            **/triggermodal.mdx
            **/about/**
            
      - name: Trigger Devin Content Review
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEVIN_WEBHOOK_TOKEN }}
          repository: ${{ github.repository }}
          event-type: devin-content-review
          client-payload: |
            {
              "pr_number": "${{ github.event.pull_request.number }}",
              "pr_title": "${{ github.event.pull_request.title }}",
              "pr_url": "${{ github.event.pull_request.html_url }}",
              "changed_files": "${{ steps.changed-files.outputs.all_changed_files }}",
              "repository": "${{ github.repository }}",
              "sender": "${{ github.event.sender.login }}",
              "action": "content_review_requested",
              "tone_guidelines_url": "https://walletconnect.notion.site/Reown-Tone-of-Voice-Messaging-Framework-1ba3a661771e8026b3e5f0006be26000"
            }
            
      - name: Add review pending comment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            const mdxFiles = changedFiles.filter(file => file.endsWith('.mdx'));
            
            if (mdxFiles.length > 0) {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🤖 Content Review Requested
                
**Devin AI has been notified to review the tone of voice for this PR.**

📝 **Files to be reviewed:** ${mdxFiles.length}
${mdxFiles.map(file => `- \`${file}\``).join('\n')}

⏳ **Status:** Review in progress...

The review will focus on:
- Tone alignment with Reown's brand guidelines
- Clear and accessible language for developers
- Professional yet approachable communication
- Consistent terminology usage

*Devin will post detailed feedback shortly. This comment will be updated when the review is complete.*`
              });
            }</mdxFiles.length>
